include:
  - authentication-microservice/.gitlab-ci.yml
  - example-microservice/.gitlab-ci.yml

gradle_build:
  extends: .build_cached
  stage: build
  cache:
    policy: pull-push
  artifacts:
    name: build
    expire_in: 6 hours
    paths:
      - build/
  script:
    - gradle build testClasses
